[versions]
kotlin = "2.3.20"
kotest = "6.1.11"
androidLibrary = "9.1.1"
bouncyCastle = "1.84"
kotlinIo = "0.9.0"
kotlinCoroutines = "1.10.2"
ksp = "2.3.6"

[libraries]

# Gradle plugins
kotlinMultiplatformPlugin = { group = "org.jetbrains.kotlin.multiplatform", name = "org.jetbrains.kotlin.multiplatform.gradle.plugin", version.ref = "kotlin" }
kotestPlugin = { group = "io.kotest", name = "io.kotest.gradle.plugin", version.ref = "kotest" }
androidLibraryPlugin = { group = "com.android.kotlin.multiplatform.library", name = "com.android.kotlin.multiplatform.library.gradle.plugin", version.ref = "androidLibrary" }
kspPlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

# Kotest
kotestAssertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotestEngine = { group = "io.kotest", name = "kotest-framework-engine", version.ref = "kotest" }
kotestRunnerJunit = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }

# Cryptography providers
bouncyCastle = { group = "org.bouncycastle", name = "bcprov-jdk18on", version.ref = "bouncyCastle" }

# Kotlinx
kotlinIo = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core", version.ref = "kotlinIo" }
kotlinCoroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
