package com.icure.kryptom.crypto

import com.icure.kryptom.utils.toHexString
import com.icure.kryptom.utils.unsafeUuidFromRandomBytes

/**
 * Cryptographically strong random generator. The implementation must be thread safe.
 */
interface StrongRandom {
	/**
	 * Generates a sequence of random bytes.
	 * @param length amount of bytes to generate
	 * @return the generated bytes.
	 */
	fun randomBytes(length: Int): ByteArray =
		ByteArray(length).also { fill(it) }

	/**
	 * Fills an array with random content.
	 */
	fun fill(array: ByteArray)

	/**
	 * Generates a random UUID.
	 * @return string representation of the uuid.
	 */
	@OptIn(ExperimentalUnsignedTypes::class)
	fun randomUUID(): String =
		unsafeUuidFromRandomBytes(randomBytes(16).toUByteArray())
}