package com.icure.kryptom.crypto

import com.icure.kryptom.utils.hexToByteArray
import com.icure.kryptom.utils.toHexString
import io.kotest.assertions.throwables.shouldThrow
import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe

/** key, message, HMAC-SHA256. RFC 4231 test cases 1-4, 6, 7 followed by edge cases (64-byte key, empty key, 65-byte key). */
private val hmacVectors: List<List<String>> = listOf(
	listOf("0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b", "4869205468657265", "b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7"),
	listOf("4a656665", "7768617420646f2079612077616e7420666f72206e6f7468696e673f", "5bdcc146bf60754e6a042426089575c75a003f089d2739839dec58b964ec3843"),
	listOf("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd", "773ea91e36800e46854db8ebd09181a72959098b3ef8c122d9635514ced565fe"),
	listOf("0102030405060708090a0b0c0d0e0f10111213141516171819", "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd", "82558a389a443c0ea4cc819899f2083a85f0faa3e578f8077a2e3ff46729665b"),
	listOf("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "54657374205573696e67204c6172676572205468616e20426c6f636b2d53697a65204b6579202d2048617368204b6579204669727374", "60e431591ee0b67f0d8a26aacbf5b77f8e0bc6213728c5140546040f0ee37f54"),
	listOf("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "5468697320697320612074657374207573696e672061206c6172676572207468616e20626c6f636b2d73697a65206b657920616e642061206c6172676572207468616e20626c6f636b2d73697a6520646174612e20546865206b6579206e6565647320746f20626520686173686564206265666f7265206265696e6720757365642062792074686520484d414320616c676f726974686d2e", "9b09ffa71b942fcb27635fbcd5b0e944bfdc63644f0713938a7f51535c3a35e2"),
	listOf("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f", "", "3499f163f48604c0b15ac89e4e7c66f314fb3b203b8ac2f564828e62f6be9d9d"),
	listOf("", "656d707479206b6579", "bf6e6a0f34cd9fdf69c67b8c62969c87cd4f783d4665217df03f062dc4a0406e"),
	listOf("4242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242", "36352d62797465206b657920697320686173686564", "203be3b22370605184677d75c3efba9997cd8e60a481933e191165e4d3986a70")
)

/** IKM, salt, info, L, PRK, OKM. RFC 5869 appendix A test cases 1-3 (SHA-256). */
private val rfc5869Vectors: List<List<String>> = listOf(
	listOf("0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b", "000102030405060708090a0b0c", "f0f1f2f3f4f5f6f7f8f9", "42", "077709362c2e32df0ddc3f0dc47bba6390b6c73bb50f9c3122ec844ad7c2b3e5", "3cb25f25faacd57a90434f64d0362f2a2d2d0a90cf1a5a4c5db02d56ecc4c5bf34007208d5b887185865"),
	listOf("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f", "606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9fa0a1a2a3a4a5a6a7a8a9aaabacadaeaf", "b0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedfe0e1e2e3e4e5e6e7e8e9eaebecedeeeff0f1f2f3f4f5f6f7f8f9fafbfcfdfeff", "82", "06a6b88c5853361a06104c9ceb35b45cef760014904671014a193f40c15fc244", "b11e398dc80327a1c8e7f78c596a49344f012eda2d4efad8a050cc4c19afa97c59045a99cac7827271cb41c65e590e09da3275600c2f09b8367793a9aca3db71cc30c58179ec3e87c14c01d5c1f3434f1d87"),
	listOf("0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b", "", "", "42", "19ef24a32c717b167f33a91d6f648bdf96596776afdb6377ac434c1c293ccb04", "8da4e775a563c18f715f802a063c5a31b8a11f5c5ee1879ec3454e5f3c738d2d9d201395faa4b61a96c8")
)

/**
 * Shared x, transcript, 64-byte OKM with salt = 32 zero bytes and info = transcript. Generated by the pairing
 * scheme's independent Python reference (`secp160r1_ref.py`).
 */
private val pairingKdfVectors: List<List<String>> = listOf(
	listOf("0000000000000000000000000000000000000000", "", "26784241251f60c567a13bb88384a23b49c844cdb660315b3cd03204ca79daadfaf62e0e49b487ab5807d5535846d852568a134e7c1cdd513bd6b17826e23d62"),
	listOf("7b76ff541ef363f2df13de1650bd48daa958bc59", "7472616e7363726970742d31", "1dea640f3ed1b6519dddc191dd374fbddb34d1b6af6fb1af1ac80ed6612a66cd6f7c405eab9f01b5cd5ebd16ae8ef8a2e3bd1fc5c2078516fe4e8e16df4cd4f7"),
	listOf("2719f7e2b867b7de06dba6bb2b90098805de45ff", "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f", "6c207281c0adc46d885721b43814ed8f3ea35294caf366d1b767d5df4e1a5248b296901bdea152970f39d7d7f41c5650ef758ab302ce11b279acf6c3dff0a7fa")
)

class HkdfSha256Test : StringSpec({
	val digest = defaultCryptoService.digest
	val hkdf = HkdfSha256(digest)

	"HMAC-SHA256 matches RFC 4231 and handles short, block-sized and over-sized keys" {
		hmacVectors.forEach { (key, message, expected) ->
			digest.hmacSha256(hexToByteArray(key), hexToByteArray(message)).toHexString() shouldBe expected
		}
	}

	"extract, expand and derive match the RFC 5869 vectors" {
		rfc5869Vectors.forEach { row ->
			val (ikm, salt, info, length, prk) = row
			val okm = row[5]
			val actualPrk = hkdf.extract(hexToByteArray(salt), hexToByteArray(ikm))
			actualPrk.toHexString() shouldBe prk
			hkdf.expand(actualPrk, hexToByteArray(info), length.toInt()).toHexString() shouldBe okm
			hkdf.derive(hexToByteArray(ikm), hexToByteArray(salt), hexToByteArray(info), length.toInt()).toHexString() shouldBe okm
		}
	}

	"derive matches the pairing reference vectors" {
		pairingKdfVectors.forEach { (sharedX, transcript, okm) ->
			hkdf.derive(
				ikm = hexToByteArray(sharedX),
				salt = ByteArray(HkdfSha256.HASH_LENGTH),
				info = hexToByteArray(transcript),
				length = 64
			).toHexString() shouldBe okm
		}
	}

	"a null salt, an empty salt and 32 zero bytes of salt are equivalent" {
		val ikm = hexToByteArray(pairingKdfVectors[1][0])
		val fromNull = hkdf.extract(null, ikm).toHexString()
		hkdf.extract(ByteArray(0), ikm).toHexString() shouldBe fromNull
		hkdf.extract(ByteArray(HkdfSha256.HASH_LENGTH), ikm).toHexString() shouldBe fromNull
	}

	"expand rejects lengths outside 1..255*HashLen and produces exactly the requested length" {
		val prk = hkdf.extract(null, ByteArray(20))
		shouldThrow<IllegalArgumentException> { hkdf.expand(prk, ByteArray(0), 0) }
		shouldThrow<IllegalArgumentException> { hkdf.expand(prk, ByteArray(0), HkdfSha256.MAX_OUTPUT_LENGTH + 1) }
		listOf(1, 31, 32, 33, 64, 100).forEach { hkdf.expand(prk, ByteArray(0), it).size shouldBe it }
		// a longer output is a prefix-extension of a shorter one with the same inputs
		val long = hkdf.expand(prk, byteArrayOf(1, 2, 3), 70)
		hkdf.expand(prk, byteArrayOf(1, 2, 3), 40).toHexString() shouldBe long.copyOf(40).toHexString()
	}
})
