"""Regenerates lib/src/commonTest/kotlin/com/icure/kryptom/crypto/ec/Secp160r1Vectors.kt from vectors.json.

Run secp160r1_ref.py first (it writes vectors.json next to itself), then this script. The `codes` and `kdf`
sections of vectors.json are not part of Secp160r1Vectors.kt: the kdf rows live inline in HkdfSha256Test.kt, the
codes rows in the pairing scheme's tests (outside kryptom). This script prints both so they can be pasted there.
"""
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parents[1] / "lib/src/commonTest/kotlin/com/icure/kryptom/crypto/ec/Secp160r1Vectors.kt"

v = json.load(open(HERE / "vectors.json"))
d = v["domain"]

def q(s):
    return f'"{s}"'

lines = []
lines.append("package com.icure.kryptom.crypto.ec")
lines.append("")
lines.append("/**")
lines.append(" * Known-answer vectors for secp160r1, generated by an independent Python reference implementation")
lines.append(" * whose scalar multiplication, ECDH and point validity were themselves cross-checked against")
lines.append(" * `python-ecdsa`'s SECP160r1 (19/19 scalar multiplications, 6/6 ECDH exchanges, 13/13 validity")
lines.append(" * decisions agreeing). Do not edit by hand: regenerate with `ref/secp160r1_ref.py`.")
lines.append(" */")
lines.append("internal object Secp160r1Vectors {")
lines.append(f"    const val P = {q(d['p'])}")
lines.append(f"    const val B = {q(d['b'])}")
lines.append(f"    const val GX = {q(d['gx'])}")
lines.append(f"    const val GY = {q(d['gy'])}")
lines.append(f"    const val N = {q(d['n'])}")
lines.append("")
lines.append("    /** u, v, u+v, u-v, u*v, u^2, u^-1 (empty when u = 0). */")
lines.append("    val field: List<List<String>> = listOf(")
for r in v["field"]:
    lines.append("        listOf(" + ", ".join(q(r[k]) for k in ("u", "v", "add", "sub", "mul", "sqr")) + f", {q(r.get('inv', ''))}),")
lines.append("    )")
lines.append("")
lines.append("    /** k, x(kG), y(kG). */")
lines.append("    val scalarMul: List<List<String>> = listOf(")
for r in v["scalarMul"]:
    lines.append(f"        listOf({q(r['k'])}, {q(r['x'])}, {q(r['y'])}),")
lines.append("    )")
lines.append("")
lines.append("    /** x, valid, even-y (empty when invalid). */")
lines.append("    val decompress: List<Triple<String, Boolean, String>> = listOf(")
for r in v["decompress"]:
    lines.append(f"        Triple({q(r['x'])}, {'true' if r['valid'] else 'false'}, {q(r.get('yEven', ''))}),")
lines.append("    )")
lines.append("")
lines.append("    /** dA, x(A), dB, x(B), shared x. */")
lines.append("    val ecdh: List<List<String>> = listOf(")
for r in v["ecdh"]:
    lines.append(f"        listOf({q(r['dA'])}, {q(r['xA'])}, {q(r['dB'])}, {q(r['xB'])}, {q(r['sharedX'])}),")
lines.append("    )")
lines.append("}")
OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT}")
print("\n// codes: version, x, expected code, checksum (for the pairing scheme tests)")
for r in v["codes"]:
    print(f'listOf("{r["version"]}", "{r["x"]}", "{r["code"]}", "{r["checksum"]}"),')
print("\n// kdf: shared x, transcript, okm64 (for HkdfSha256Test)")
for r in v["kdf"]:
    print(f'listOf("{r["sharedX"]}", "{r["transcript"]}", "{r["okm64"]}"),')
